task:
  name: Windows
  windows_container:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
  env:
    CIRRUS_SHELL: powershell
    CHOCOLATEY_HOME: C:\ProgramData\chocolatey
    # SQLITE_HOME: C:\ProgramData\chocolatey\lib\SQLite
    GIT_HOME: C:\Program Files\Git
    # PATH: '$PATH;$USERPROFILE\AppData\Local\Microsoft\dotnet;$CHOCOLATEY_HOME\bin;$SQLITE_HOME\tools;$GIT_HOME\cmd'
    DOTNET_ROOT: $USERPROFILE\AppData\Local\Microsoft\dotnet
    PATH: '$PATH;$USERPROFILE\AppData\Local\Microsoft\dotnet;$CHOCOLATEY_HOME\bin;$GIT_HOME\cmd;'
  install_dotnet_sdk_script: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) -Channel Current"
  check_dotnet_version_script: dotnet --info; 
  install_choco_script: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  check_choco_version_script: choco upgrade pgkname --noop
  # install_sqlite_script: choco install sqlite -y
  # check_sqlite_version_script: sqlite3 -version
  install_git_script: choco install git -y
  git_submodule_update_init_script: git submodule update --init --recursive
  test_script: cd Kinvey.Tests; dotnet test; exit $LastExitCode