language: csharp
solution: Kinvey-Xamarin.sln
script:
 - xbuild Kinvey-Xamarin/Kinvey-Xamarin.csproj 
 - xbuild TestFramework/Tests.Integration/Tests.Integration.csproj
 - mono TestFramework/Tools/Gaillard.SharpCover/bin/Debug/SharpCover.exe instrument config.json
 - mono packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe TestFramework/Tests.Integration/bin/Debug/Tests.Integration.dll
after_success:
- mono TestFramework/Tools/Gaillard.SharpCover/bin/Debug/SharpCover.exe check
- bash <(curl -s https://codecov.io/bash)
