language: csharp
solution: Kinvey.sln
install:
 - wget -O pubnub.zip https://www.nuget.org/api/v2/package/PubnubNetPlatform/3.8.7
 - echo `pwd`
 - sudo mkdir packages/pubnubnetplatform.3.8.7
 - sudo mv pubnub.zip packages/pubnubnetplatform.3.8.7/.
 - sudo unzip packages/pubnubnetplatform.3.8.7/pubnub.zip
 - echo `ls -l packages/pubnubnetplatform.3.8.7/lib`
 - nuget restore Kinvey.sln
script:
 - xbuild Kinvey.Core/Kinvey.Core.csproj 
 - xbuild TestFramework/Tests.Integration/Tests.Integration.csproj
 - mono packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe TestFramework/Tests.Integration/bin/Debug/Tests.Integration.dll
