install_coverlet: &install_coverlet dotnet tool install --global coverlet.console && export PATH="$PATH:/home/travis/.dotnet/tools"
matrix:
  include:
    - name: "Linux"
      os: linux
      language: csharp
      mono: none
      dotnet: 2.1
      before_script:
        - sudo apt update
        - sudo apt install tree
        - *install_coverlet
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F Linux
    - name: "macOS"
      os: osx
      language: generic
      osx_image: xcode9.4
      before_script:
        - brew update
        - brew install tree
        - brew cask install dotnet-sdk
        - export PATH="$PATH:/usr/local/share/dotnet"
        - *install_coverlet
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F macOS
    - name: "Mono"
      language: csharp
      solution: Kinvey.sln
      install:
        - nuget restore Kinvey.sln
      script:
        - msbuild Kinvey.Core/Kinvey.Core.csproj
        - msbuild TestFramework/Tests.Integration/Tests.Integration.csproj
        - mono packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe TestFramework/Tests.Integration/bin/Debug/Tests.Integration.dll
script:
  - cd Kinvey.Tests; dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
