language: csharp
mono: none
dotnet: 2.1
before_script:
- dotnet tool install --global coverlet.console
- export PATH="$PATH:/home/travis/.dotnet/tools"
script:
- cd Kinvey.Tests; dotnet test
- coverlet bin/Debug/netcoreapp2.1/Kinvey.Tests.dll  --target "dotnet" --targetargs "test $PWD --no-build"
after_success:
- bash <(curl -s https://codecov.io/bash)
