matrix:
  include:
    - name: "Linux"
      os: linux
      language: csharp
      mono: none
      dotnet: 2.1
      env:
        - PLATFORM=Linux
    - name: "macOS"
      os: osx
      language: generic
      osx_image: xcode9.4
      env:
        - PLATFORM=macOS
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install tree; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install dotnet-sdk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="$PATH:/usr/local/share/dotnet"; fi
  - dotnet tool install --global coverlet.console
  - export PATH="$PATH:/home/travis/.dotnet/tools"
script:
  - cd Kinvey.Tests; dotnet test
  - tree bin
  - ~/.dotnet/tools/coverlet bin/$PLATFORM/Debug/netcoreapp2.1/Kinvey.Tests.dll  --target "dotnet" --targetargs "test $PWD --no-build" --format opencover
after_success:
  - bash <(curl -s https://codecov.io/bash) -n $PLATFORM
