language: csharp
solution: Kinvey.sln
install:
 - wget -O pubnub.zip https://www.nuget.org/api/v2/package/PubnubNetPlatform/3.8.7
 - mv pubnub.zip packages/.
 - unzip packages/pubnub.zip
 - nuget restore solution-name.sln
script:
 - xbuild Kinvey.Core/Kinvey.Core.csproj 
 - xbuild TestFramework/Tests.Integration/Tests.Integration.csproj
 - mono packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe TestFramework/Tests.Integration/bin/Debug/Tests.Integration.dll
